// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:25574e1b-d542-471a-9beb-d6e190601e26",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fOuAXxQBg",
    "aws_user_pools_web_client_id": "3h3p9qrh2fdq85hh8m3baa079m",
    "aws_appsync_graphqlEndpoint": "https://dkypdek5yfg2pk554is6oypnlq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
